version: '3.3'
services:
  redis_service:
    image: redis
    command: redis-server --appendonly yes
    ports:
        - "6379:6379"
    volumes:
    - ./data/redis:/data
    restart: unless-stopped