#
# Production docker compose file, should be run directly on the raspberry pi.
# Run with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
#
version: '3.3'

services:
  nucuhub_sensors:
    restart: on-failure
    privileged: true
    depends_on:
      - redis_service
    build:
      context: .
      dockerfile: ./nucuhub/sensors/Dockerfile
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - "/sys:/sys"
    networks:
      - nucuhub
  nucuhub_monitoring:
    restart: on-failure
    depends_on:
      - redis_service
    build:
      context: .
      dockerfile: ./nucuhub/monitoring/Dockerfile
    networks:
      - nucuhub
  nucuhub_backend:
    restart: on-failure
    depends_on:
      - redis_service
      - nucuhub_sensors
    build:
      context: .
      dockerfile: ./nucuhub/backend/Dockerfile
    ports:
      - 8080:8080
    networks:
      - nucuhub